### PR TITLE
update kfservice status URL

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

Background:  After introducing `apis.URL` to status in the #251, we have to create this hack since that struct is deep in go standard [net library](https://github.com/golang/go/blob/a2f5d644d3a2903a82e527e3bca2c4bdff1d0750/src/net/url/url.go#L359) and we can not add openapi annotation, @yuzisun suggests creating our simplified URL struct. After investigation, I think that's better to back to `string` for URL since if we ceate our URL struct, that's hard to assign with net.url (cannot sure no issue in the future). And there is a [String function](https://github.com/knative/pkg/blob/d3c17af1d97a4dd7f0167628df312f1e9889f444/apis/url.go#L69) in the knative.dev/pkg/apis.URL, we can use that and transfer to string for kfservice. That's good enough for kfservice. 

See more details in the #272

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/289)

### CODE REVIEW

**Comment by jinchihe** [comment]
/cc @yuzisun 
/cc @johnugeorge 

Could you please help to take a look? Thanks.

**Comment by yuzisun** [comment]
Sounds good to me, want to hear @johnugeorge’s  thoughts.

**Comment by johnugeorge** [comment]
Looks good to me.
/cc @ellis-bigelow 
@ellis-bigelow had a comment in my initial PR to keep the same status type as the knative.

**Comment by yuzisun** [comment]
Discussed with Ellis we can always extend if needed.
/approve

**Pull request merged**
