### PR TITLE
update from v1alpha1 to v1alpha2 for some docs and samples

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
After I installed the last KFServing, and try to deploy KFService using sample, but failed due to the mismatched version. The PR is to update from v1alpha1 to v1alpha2 for some docs and samples.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/308)

### CODE REVIEW

**Comment by jinchihe** [comment]
/assign @yuzisun 

Please take a look, thanks!

**Comment by rakelkar** [comment]
/hold
Wait for #300 so that samples can be updated to account for the breaking change?

**Comment by yuzisun** [comment]
> /hold
> Wait for #300 so that samples can be updated to account for the breaking change?

Agreed, let's hold this until v1alpha2 changes are finalized.

**Comment by jinchihe** [comment]
/hold cancel

Since #300 has been merged.

**Comment by rakelkar** [comment]
/hold

I've made most of these changes in #327 as well as part of modifying the files to use storageUri instead of modelUri..

**Comment by yuzisun** [comment]
@jinchihe we can close this now. @rakelkar did it in https://github.com/kubeflow/kfserving/pull/327

**Pull request closed without merging**
