### PR TITLE
Added licenses.

### LINKED ISSUE #640: Add licenses for dependencies of all KFServing Images
Images:
* gcr.io/kfserving/xgbserver:0.2.2
* gcr.io/kfserving/sklearnserver:0.2.2
* gcr.io/kfserving/pytorchserver:0.2.2
* gcr.io/kfserving/alibi-explainer:0.2.2
* gcr.io/kfserving/storage-initializer:0.2.2
* gcr.io/kfserving/logger:0.2.2
* gcr.io/kfserving/kfserving-controller:0.2.2

### PR DESCRIPTION
**Pull request by ellis-bigelow**
Fixes #640

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/646)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@ellis-bigelow can we add instructions as well so to be able to update in future?

**Comment by ellis-bigelow** [comment]
Yeah I added a script for this. See hack/generate-licenses.

**Pull request merged**
