### PR TITLE
Improve documentation to include `requests` dependency

### PR DESCRIPTION
**Pull request by iamshwin**
**What this PR does / why we need it**:
Improve documentation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Release note**:
```NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/577)

### CODE REVIEW

**Comment by iamshwin** [comment]
@googlebot I signed it! 
/assign @yuzisun

**Comment by iamshwin** [comment]
@googlebot I signed it!

**Comment by yuzisun** [comment]
@iamshwin make sure you signed with the right email address.

**Comment by ellis-bigelow** [comment]
Thanks for the fix! /lgtm /approve

**Comment by yuzisun** [comment]
@iamshwin Can you fix the cla issue with this [link](https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions-(FAQs)#ive-signed-a-cla-why-does-github-have-an-x-on-my-commit-and-it-says-failure-need-a-cla-for-one-or-more-commit-authors-when-i-hover-over-the-x) so we can merge this?

**Comment by iamshwin** [comment]
@googlebot I signed it!

**Comment by yuzisun** [comment]
@iamshwin looks like this needs a rebase to merge in.

**Comment by iamshwin** [comment]
@googlebot I consent.

**Comment by yuzisun** [comment]
@iamshwin looks it is not rebased properly ?

**Comment by iamshwin** [comment]
@googlebot I consent.

**Comment by yuzisun** [comment]
@iamshwin let’s close this and recreate the PR?

**Comment by iamshwin** [comment]
Ok, I've put in #690.

**Pull request closed without merging**
