### PR TITLE
docs: fixes gsutil command in the End to end kafka inference example

### LINKED ISSUE #1439: CommandException: No URLs matched: gs://kfserving-examples/models/mnist
/kind bug 

I would like to run the kafka mnist example but when I run:
```bash
gsutil cp gs://kfserving-examples/models/mnist .
```
As per the readme, I get
```
CommandException: No URLs matched: gs://kfserving-examples/models/mnist
```

**What did you expect to happen:**
I expected to be able to download the model checkpoint.

### PR DESCRIPTION
**Pull request by kmarquardsen**
…inio and Kafka

**Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):**
Fixes #1439

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by theofpa** [comment]
Thanks @kmarquardsen !
/lgtm

**Comment by kmarquardsen** [comment]
@theofpa would you be able to approve running those additional workflows?

**Pull request merged**
