### PR TITLE
Add kustomize overlay for standalone installation (master)

### LINKED ISSUE #976: Add kustomize overlay for kubeflow
/kind feature
Currently Standalone KFServing installs in `kfserving-system` namespace while kubeflow installs kfserving in `kubeflow` namespace, the difference between standalone and kubeflow installation for KFServing is really minor with the [gateway configuration](https://github.com/kubeflow/kfserving/blob/master/config/configmap/inferenceservice.yaml#L66) besides the namespace. So we'd like to publish the kfserving deployment manifest for kubeflow along side with standalone manifest, this gives user an easy upgrade experience by applying the KFServing release yaml directly if they want to get onto the edge of KFServing.

**Describe the solution you'd like**
We can create a kubeflow kustomize overlay under KFServing config directory and publishes the yaml for every KFServing release.
- Kustomize namespace to `kubeflow`
- Kustomize KFServing [configmap gateway](https://github.com/kubeflow/kfserving/blob/master/config/configmap/inferenceservice.yaml#L66) to `kubeflow-gateway.kubeflow`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by jazzsir**
- replace the namespace where kfserving is deployed with kubeflow
- replace KFServing configmap gateway with kubeflow-gateway.kubeflow.

Fixes #976

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by pugangxa** [comment]
If I understand correctly, in #976 @yuzisun means to add and overlay for kubeflow while retain the existing standalone one. Also we need change the document for kubeflow user.
Another thing is, I saw 3 PR for released version too, in my opinion we need not do that.

**Comment by jazzsir** [comment]
@pugangxa, Thank you for your comments, 

> If I understand correctly, in #976 @yuzisun means to add and overlay for kubeflow while retain the existing standalone one. Also we need change the document for kubeflow user.

To retain existing namespace(kfserving-system), some values need to be parameterized.
[certificate.yaml](https://github.com/kubeflow/kfserving/blob/master/config/certmanager/certificate.yaml#L18
), [webhookcainjection_patch.yaml](https://github.com/kubeflow/kfserving/blob/master/config/default/webhookcainjection_patch.yaml#L8
)... and so on. I will apply them.

> Another thing is, I saw 3 PR for released version too, in my opinion we need not do that.

@yuzisun mentioned "publishes the yaml for every KFServing release", so I judged the way of deployment would be changed as pipeline's one as below by releasing a improved version of each branch containing these yamls,
https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines

I will update the document, as soon as the way of deployment is determined. 

Please let me know what I misinterpreted.

**Comment by pugangxa** [comment]
> @pugangxa, Thank you for your comments,
> 
> > If I understand correctly, in #976 @yuzisun means to add and overlay for kubeflow while retain the existing standalone one. Also we need change the document for kubeflow user.
> 
> To retain existing namespace(kfserving-system), some values need to be parameterized.
> [certificate.yaml](https://github.com/kubeflow/kfserving/blob/master/config/certmanager/certificate.yaml#L18), [webhookcainjection_patch.yaml](https://github.com/kubeflow/kfserving/blob/master/config/default/webhookcainjection_patch.yaml#L8)... and so on. I will apply them.
> 
Yes we should retain it for standalone kfserving deployment and these part will need overlay. 

> > Another thing is, I saw 3 PR for released version too, in my opinion we need not do that.
> 
> @yuzisun mentioned "publishes the yaml for every KFServing release", so I judged the way of deployment would be changed as pipeline's one as below by releasing a improved version of each branch containing these yamls,
> https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines
> 
OK, I am OK to commit it to different versions.

> Please let me know what I misinterpreted.
> I will update the document, as soon as the way of deployment is determined.

**Comment by ellistarn** [comment]
I'm hesitant to deploy to the kubeflow namespace. Many of our users consume us standalone as well. One of the challenges of working with kubeflow is that it's so heavyweight -- I'm much more interested in pursuing an option where we never deploy to the kubeflow namespace..

**Comment by yuzisun** [comment]
@jazzsir thanks for taking on this, the default should be still standalone installation in `kfserving-system` namespace, the intention of the original issue is to add another kustomize overlay to allow deploying to kubeflow namespace for users who are using Kubeflow and like to get on to the newer releases of KFServing. I think the change here would be making the namespace kustomizable instead of current way hardcoding the namespace everywhere.

**Comment by jazzsir** [comment]
@yuzisun @ellistarn thanks, I will make the namespace kustomizable

**Comment by jazzsir** [comment]
I tested it with gcr.io/kfserving/kfserving-controller:v0.4.0, because with the latest version, failed to run the controller.
```
{"level":"error","ts":1599011472.7178133,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"TrainedModel.serving.kubeflow.org","error":"no matches
for kind \"TrainedModel\" in version \"serving.kubeflow.org/v1beta1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-$untime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs$k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/in$ernal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.g$:477"}
{"level":"error","ts":1599011472.7179267,"logger":"entrypoint","msg":"unable to run the manager","error":"no matches for kind \"TrainedModel\" in version \"serving.kubeflow.org/v1beta1\"","stacktrace":"github.c$m/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/kfserving/cmd/manager/main.go:145\nruntime.main\n\t/usr/local/go/src/runtime$proc.go:203"}
```

**Comment by yuzisun** [comment]
@jazzsir you might want to run following commands
```
git fetch upstream
git rebase upstream/master
```

**Comment by yuzisun** [comment]
@jazzsir Can you help rebase the PR ?

**Comment by jazzsir** [comment]
Close it, because of a problem with rebase, and it will be recreated.

**Pull request closed without merging**
