### PR TITLE
Cherrypick #1525 to release-0.5

### PR DESCRIPTION
**Pull request by yuzisun**
…updated (#1525)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
@wengyao04 Can you help consent the CLA and approve this?

**Review by wengyao04 — APPROVED** [review]

**Comment by wengyao04** [comment]
@googlebot I consent

**Pull request merged**
