### PR TITLE
Release the logger image

### PR DESCRIPTION
**Pull request by pugangxa**
**What this PR does / why we need it**:
I saw the logger is already in the configmap, but checked it's not released so we cannot use the image yet.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/570)

### CODE REVIEW

**Comment by cliveseldon** [comment]
Great. Not sure how I missed this. Thanks for adding.

**Comment by pugangxa** [comment]
Why is this not auto merged? Seems all checks have passed...

**Comment by jinchihe** [comment]
Try to retest? That's strange...

/retest

**Pull request merged**
