### PR TITLE
Set max_buffer_size to tornado

### PR DESCRIPTION
**Pull request by valentin-stefan-popa**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/665)

### CODE REVIEW

**Comment by yuzisun** [comment]
@valentin-stefan-popa can you help sign the  CLA?

/ok-to-test

**Comment by valentin-stefan-popa** [comment]
> @valentin-stefan-popa can you help sign the CLA?
> 
> /ok-to-test

I follow steps from this link: https://github.com/kubernetes/community/blob/master/CLA.md and sign in
I also submit my signature.
What else do I need to do?

**Comment by valentin-stefan-popa** [comment]
@googlebot I signed it!

**Comment by yuzisun** [comment]
@valentin-stefan-popa you signed the wrong one, it is the google cla https://cla.developers.google.com/ . Please also reference the original issue on the PR description, looks it passed all the tests, have you verified if that solved your problem?

**Comment by valentin-stefan-popa** [comment]
I signed also here: https://cla.developers.google.com/clas

**Comment by valentin-stefan-popa** [comment]
No idea what do do more for this "cla/google — Need a CLA for one or more commit authors"

**Comment by yuzisun** [comment]
> No idea what do do more for this "cla/google — Need a CLA for one or more commit authors"

Do you have signed email address associated with the git commit ?

**Comment by valentin-stefan-popa** [comment]
Yes. On github I use v.valentin.popa@gmail.com and here: https://cla.developers.google.com/clas same

**Comment by yuzisun** [comment]
> Yes. On github I use [v.valentin.popa@gmail.com](mailto:v.valentin.popa@gmail.com) and here: https://cla.developers.google.com/clas same

Are you sure ? https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions-(FAQs)#ive-signed-a-cla-why-does-github-have-an-x-on-my-commit-and-it-says-failure-need-a-cla-for-one-or-more-commit-authors-when-i-hover-over-the-x

**Comment by valentin-stefan-popa** [comment]
finally I managed CLA. What is next?

**Comment by yuzisun** [comment]
> finally I managed CLA. What is next?

Cool! Looks good to me, just want to confirm if you have tested to make sure that fixes your problem ?

**Comment by valentin-stefan-popa** [comment]
No I never test it. 
How I can test it locally? I start from this example: https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer but that is going to lib not to master code. How I can do that example to point to master code?

Also I use bellow code for docker:
`FROM python:3.7-slim

COPY . .
RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev
RUN pip install --upgrade pip && pip install kfserving && pip install opencv-python && pip install SimpleITK
RUN pip install -e .
ENTRYPOINT ["python", "-m", "image_transformer"]`

How I can point docker to point to master code when I create container?

**Comment by valentin-stefan-popa** [comment]
I was able to test it locally. I change this: "import kfserving" with "from python.kfserving import kfserving" and now point to my local code instead lib. I start application locally and made a post from postman at this link: http://localhost:8080/v1/models/model:predict with my big json file and with default setting which is now 100MB I get "http1connection:289] Malformed HTTP message from ::1: Content-Length too long" because my file is 107MB but if I start application with this parameter "--max-buffer-size=209715200" and error is gone and I enter in preprocessing method. So I consider that problem is fixed.

Now when I test it locally I observe that I write buffer size like this:
"parser.add_argument('--max-buffer-size', default=DEFAULT_MAX_BUFFER_SIZE, type=int,
                    help='The max buffer size for tornado.')"
and yours are like this:
"parser.add_argument('--http_port', default=DEFAULT_HTTP_PORT, type=int,
                    help='The HTTP Port listened to by the model server.')
parser.add_argument('--grpc_port', default=DEFAULT_GRPC_PORT, type=int,
                    help='The GRPC Port listened to by the model server.')"

So do I have to change "--max-buffer-size" into "--max_buffer_size" ?

Also please answer me at problem 2 with docker. How to create docker with master code instead lib because I want to test also PVC fix from here: https://github.com/kubeflow/kfserving/pull/643/commits/f37afab889324467ac6b00b2bb7649736432d1e2

**Comment by yuzisun** [comment]
Python arg parser converts dash to understore so let's change to `--max_buffer_size` to be consistent then. 

For the PVC issue you can follow https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md to run `deploy-dev` to deploy from master.

**Comment by valentin-stefan-popa** [comment]
Changed "--max-buffer-size" to "--max_buffer_size"

**Comment by yuzisun** [comment]
@valentin-stefan-popa Thanks for the contribution!

/lgtm
/approve

**Comment by valentin-stefan-popa** [comment]
@yuzisun Thank you also for your help and hope I can help any time is need since now I know what is CLA and other things :)
Do I have to delete this branch?

**Comment by yuzisun** [comment]
That's great! The branch is in your fork so up to you :).

**Pull request merged**
