### PR TITLE
Feature: Upgrade torchserve to 0.4.1

### LINKED ISSUE #1619: Installing additional dependencies makes a 'Custom pip package install failed' error
/kind bug

**What steps did you take and what happened:**
1. I added ```import pytorch_lightning``` code to the torchserve tutorial ```mnist.py``` file (https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/torchserve/model-archiver/model-store/mnist/mnist.py). So my ```mnist.py``` file is below.

```
import torch
from torch import nn
import torch.nn.functional as F
import pytorch_lightning


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.dropout1 = nn.Dropout2d(0.25)
        self.dropout2 = nn.Dropout2d(0.5)
        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.max_pool2d(x, 2)
        x = self.dropout1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output
```

2. My ```config.properties``` file is below.
```
inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8081
number_of_netty_threads=4
job_queue_size=10
service_envelope=kfserving
install_py_dep_per_model=true
model_store=/mnt/models/model-store
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"mnist":{"1.0":{"defaultVersion":true,"marName":"mnist.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":120}}}}
```

3. My ```requirements.txt``` file is below.
```
pytorch-lightning
```

4. I made ```mnist.mar``` file through the below command.
```
torch-model-archiver --model-name mnist --version 1.0 --model-file model-archiver/model-store/mnist/mnist.py --serialized-file model-archiver/model-store/mnist/mnist_cnn.pt --handler model-archiver/model-store/mnist/mnist_handler.py --export-path model-store -f -r requirements.txt
```

5. When I deploy an mnist inference server with the above ```config.properties``` and ```mnist.mar``` files, the following error message is shown
```
2021-05-20 08:29:39,556 [ERROR] main org.pytorch.serve.snapshot.SnapshotManager - Error while registering model. Details: Custom pip package installation failed for mnist
```
and the result of an input request is below.
```
*   Trying 192.168.64.13:32607...
* TCP_NODELAY set
* Connected to 192.168.64.13 (192.168.64.13) port 32607 (#0)
> POST /v1/models/mnist:predict HTTP/1.1
> Host: torchserve-mnist.default.example.com
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 401
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 401 out of 401 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 93
< content-type: text/html; charset=UTF-8
< date: Thu, 20 May 2021 08:32:58 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 88
<
* Connection #0 to host 192.168.64.13 left intact
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```

**What did you expect to happen:**
I expected successful installation of dependencies (```pytorch-lightning```). 

**Anything else you would like to add:**
The above descriptions involve installing ```pytorch-lightning``` dependency. The same error is shown when installing ```pytorch``` dependency through ```requirements.txt``` (even though ```pytorch``` is installed by-default as a part of ```torchserve``` setup). However, installing ```omegaconf``` and ```mutagen``` dependencies shows no error.

**Environment:**

I used ```minikube``` cluster, and installed necessary dependencies through the following command: ```bash ./hack/quick_install.sh```

- Minikube version: v1.19.0
- Kubernetes version: (use `kubectl version`): v1.17.11
- OS (e.g. from `/etc/os-release`): macOS Big Sur v11.3.1

### PR DESCRIPTION
**Pull request by jagadeeshi2i**
Upgrade torchserve version to 0.4.1

Fixes  #1619

### CODE REVIEW

**Review by chauhang — APPROVED** [review]

**Comment by yuzisun** [comment]
@jagadeeshi2i can you help update the torchserve version in the table ? https://github.com/kubeflow/kfserving/blob/master/docs/samples/README.md#deploy-inferenceservice-with-predictor

**Pull request merged**
