### PR TITLE
Cut 0.2.2 release

### PR DESCRIPTION
**Pull request by ellis-bigelow**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/579)

### CODE REVIEW

**Comment by yuzisun** [comment]
third time is a charm!
/retest

**Comment by animeshsingh** [comment]
Probably something broken in alibi
Screen Shot 2019-11-26 at 6 27 49 PM

**Comment by animeshsingh** [comment]
Dependent on this (I believe) 
https://github.com/kubeflow/manifests/pull/631

and @hougangliu will do one on profile controller to Kubeflow

**Pull request merged**
