### PR TITLE
allow configurable region name

### PR DESCRIPTION
**Pull request by harshavardhana**
**What this PR does / why we need it**:
Configuration region-name to avoid get_bucket_location API calls, some users
may have restricted policies, thus allow for these situations. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ellistarn** [comment]
Nice fix! Thanks!

**Comment by ace-gabriel** [comment]
Nice fix! Solved our issue.

Our issue was that KFServing gets access denied error when downloading the model from bucket using Minio client. Turned out that we don't have get_bucket_location access. This will avoid similar issue

**Comment by yuzisun** [comment]
thanks @harshavardhana for the prompt fix!

**Pull request merged**
