### PR TITLE
Feast Integration for OOTB Transformers

### PR DESCRIPTION
**Pull request by ellistarn**
**What this PR does / why we need it**:
Implements our first OOTB transformer. FEAST is a rising FEAture STore in the OSS community. I had the pleasure of working in a hackathon this week with engineers from their team. 

This PR is pretty big. I'm happy to break it up, but there are multiple axes I could do so. If you're happy reviewing as is, great, otherwise, you need only ask.

1. Implemented the FeastSpec in the KFService
2. Implemented the FeastTransformer backend python server.
3. I cleaned up a ton of code I found that was odd along the way (sorry not sorry)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/389)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Cutting off this PR here. Please take a look. I plan to implement a better sample soon. This feature should be considered experimental until Feast 0.3 releases officially. 

@yuzisun 
@rakelkar

**Comment by ellis-bigelow** [comment]
@googlebot I consent.
/cla ok

**Comment by animeshsingh** [comment]
@ellis-bigelow I believe we are not targeting this for v0.2?

**Comment by ellis-bigelow** [comment]
Correct

**Comment by irvifa** [comment]
By the way is this on the milestone? Would like to try feast and stumbled on this PR. Seems like there's also a lot of conflicts.

**Comment by ellis-bigelow** [comment]
This work was deprioritized, and needs to be rebased with modern KFServing and FEAST. Feel free to file an issue describing our usecase around this -- we want to make sure we get it right.

**Comment by Joostrothweiler** [comment]
@ellistarn was this ever reconsidered for prioritization? I found some traces of feast transformers (`pkg/apis/serving/v1alpha2/configmap.go`) and am curious to know if the plan is still to have this as a standard transformer?

**Comment by ellistarn** [comment]
Hey @Joostrothweiler, I'd need to sync with the Gojek team on this, and I'm struggling to find time. No plans so far, and this is definitely quite outdated compared to how far FEAST's interface has moved. Would love a champion to drive this.

**Comment by ellistarn** [comment]
@woop thoughts?

**Comment by woop** [comment]
> @woop thoughts?

From a Feast API perspective I think it should be pretty easy to update. Let me reach out to the team to see if there is appetite to pick this up.

**Comment by ellistarn** [comment]
Apologies. I just rewrote history to fix the contributors list. This PR needs a rebase before it can be reopened.

**Pull request closed without merging**
