### PR TITLE
Added annotation to use anonymous credentials for s3

### PR DESCRIPTION
**Pull request by abchoo**
**What this PR does / why we need it**: Adds option to use anonymous credentials for s3 to access public buckets

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by yuzisun** [comment]
@abchoo is it possible to add an e2e test for S3 ?

**Comment by abchoo** [comment]
> @abchoo is it possible to add an e2e test now for S3 with this?

Yes, as long as the bucket allows public access this should work.

**Comment by yuzisun** [comment]
/lgtm
/approve

Thanks @abchoo !

**Pull request merged**
