### PR TITLE
Replace minio library with boto3 for S3 access

### PR DESCRIPTION
**Pull request by dylanpiergies**
Using boto3 for access to S3 buckets offers greater flexibility with
regard to authentication with the S3 API. In particular, it does not
require (although does support) the use of key ID/secret access key
style credentials; this makes it possible to use IAM roles assigned to
worker nodes or Kubernetes service accounts, thus eliminating the need
to pass authentication credentials to the application via Kubernetes
secrets or environment variables.

The environment variables used by the previous implementation match
those considered by the boto3 library out of the box, so existing
functionality is unaffected.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/628)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
@animeshsingh what do you think of this change? I think minio may be overkill right now. Happy to use cloud specific libraries.

**Comment by ellis-bigelow** [comment]
Thank you for your PR Dylan!

**Comment by animeshsingh** [comment]
@ellis-bigelow @dylanpiergies I think minio is the most commonly used s3 development cli used, is also present in kubeflow installation being used by kubeflow pipelines, and the minio server also gets deployed through kubeflow pipelines. Ideally we should expand this support, and provide an optional minio server which folks can use for local development as well.....

**Comment by dylanpiergies** [comment]
@ellis-bigelow @animeshsingh I was led to this code because I was still seeing the issues described in #213 and #749. This was due to the incomplete default URI here:
https://github.com/kubeflow/kfserving/blob/a70ab5740cbbe148c3c1ff560e358dfcb08f210d/python/kfserving/kfserving/storage.py#L212
The absence of the scheme (e.g. `https://`) causes `urlparse` to (silently) parse the URL incorrectly, which causes problems later. That could easily be fixed, of course.

The real motivation for this change is the lack of support for IAM-based authentication in Minio. IAM auth eliminates the need to manage credentials, which is quite a big win for the security conscious. And more convenient.

I can see from previous comments that this change could have broader implications than I was aware of. This MR would need further work in any case, but it's useful to hear initial feedback.

The value of using boto3 is that it's the officially supported Python client, meaning it'll behave as any engineer experienced with AWS would expect, e.g. reading influential environment variables, config files, etc. It's not as lean as it could be, but it "just works".

What's the driver behind the Minio client?

**Comment by dylanpiergies** [comment]
@googlebot I signed it!

**Comment by dylanpiergies** [comment]
@googlebot I fixed it.

**Comment by animeshsingh** [comment]
> The value of using boto3 is that it's the officially supported Python client, meaning it'll behave as any engineer experienced with AWS would expect, e.g. reading influential environment variables, config files, etc. It's perhaps not as lean as it could be, but it "just works".

its the same with minio client. Just works! Also please go through some comments here
https://github.com/minio/minio-py/issues/560

Its a strong community, supported as well. We are even using it with IBM COS
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-minio

**Comment by dylanpiergies** [comment]
> its the same with minio client.

Not exactly. The Minio client is does not support all of the functionality available in AWS (in particular, IAM authentication). It doesn't automatically configure itself in the same way other AWS clients do, as I've mentioned, such as by reading standard config files in environment variables. Whilst I'd agree that it could be nice if AWS split up boto3 into individual components like the Azure client libraries, the boto3 library isn't particularly heavyweight.

There is an issue against minio-py (closed 6 hours ago at the time of writing) that looks like it's addressing this here: https://github.com/minio/minio-py/issues/814, so maybe this has been rolled out into a new release. I'll check this out.

Either way, being forced to provide an access key ID and secret key is an unnecessary evil when you're accessing S3 from within AWS. You shouldn't have to provide any credentials or configuration for this to work.

**Comment by animeshsingh** [comment]
@dylanpiergies if you have a strong usecase to use with AWS, we can consider it. Until then, as I mentioned, we see more of Kubeflow community using Minio, and even with IBM COS the options supported seems [AWSCLI](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-aws-cli) or Minio. How does boto3 compare with AWSCLI?

**Comment by animeshsingh** [comment]
and seems the AWS IAM support got added in Minio as well? 
https://github.com/minio/minio-py/pull/817

**Comment by dylanpiergies** [comment]
@animeshsingh Well, the AWS CLI and boto3 serve different use cases. The AWS CLI is intended for use on the command line or from shell scripts, whilst boto3 is a Python library intended for use within Python applications. The AWS CLI is itself written in Python and actually uses botocore (the lower-level library wrapped by boto3) under the hood!

Yes, it looks like the feature I'm particularly interested in has been recently implemented (see comment above). It's still pending on my end to check it's all hanging together correctly. I'm not sure if this will also work with [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), since I'm not sure of the mechanics behind that. I'm using IAM roles assigned to nodes at the moment (as it was easier) but as we start to tighten security we'll want to be assigning those to individual pods. I'll do some more digging around this.

**Comment by ellis-bigelow** [comment]
I'll mostly leave it to you two to sort this out, but if you find your use case isn't supported by Minio, especially if it's around increasing security, we should absolutely bring in boto3 to resolve this. 

Our philosophy around our dependency graph is to keep things as unified and simple as possible. Minio helps us to achieve that, but that said, libraries like this can often fall behind, and we don't want to fall off the cutting edge.

**Comment by ellis-bigelow** [comment]
Still there @dylanpiergies @animeshsingh ?
/retest

**Comment by dylanpiergies** [comment]
> Still there @dylanpiergies @animeshsingh ?
> /retest

Sorry, my focus shifted away from this and into some plain old microservice DevOps engineering. Anyway, after some digging, it seems that the Python MinIO client has now been updated with the missing functionality, so I'm just closing this. I think a much more minor code change may still be required to enable this to work correctly in the use case we had, but it looks like that project might be dead in the water anyway.

**Comment by ellis-bigelow** [comment]
Hey thanks for your effort anyways! Hope our paths cross again.

**Pull request closed without merging**
