### PR TITLE
Enabled go lint.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/126)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Nice! Where does the hack script come from? Did you just write it?

**Comment by gyliu513** [comment]
> Nice! Where does the hack script come from? Did you just write it?

@ellis-bigelow I got it from https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/hack/verify-golint.sh and have just enabled this for katib as well https://github.com/kubeflow/katib/blob/master/hack/verify-golint.sh

**Pull request merged**
