### PR TITLE
Renamed KFService to InferenceService

### LINKED ISSUE #317: Discuss: Rename KFService to MLService
We've discussed this idea before, opening an issue to discuss in the context of v1alpha2.

### Rationale:
KFServing as it currently stands defines an API spec and an implementation for serving. The spec models the ML domain but is not dependent on Kubeflow in any way. MLServing is a clearer name that reinforces the loose coupling of the API. 

wdyt?

### PR DESCRIPTION
**Pull request by ellis-bigelow**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #317

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/421)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@ellis-bigelow do we have an update SDK also ready to be uploaded to pypi? Tested?

**Comment by animeshsingh** [comment]
Also @jinchihe would it require changes on Fairing side? I am pretty sure this needs changes on Pipelines integration work

**Comment by ellis-bigelow** [comment]
we will need to fast follow with these changes.

**Comment by jinchihe** [comment]
@animeshsingh Yes, that's needed in Fairing, I think we also need to update SDK name, will do that with high priority. Thanks.

**Pull request merged**
