### PR TITLE
Update KFServing 0.4 API docs

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cliveseldon** [comment]
@yuzisun How did you generate the html for the API?  Shame it misses listing the string types such as LoggerMode.
/lgtm

**Comment by yuzisun** [comment]
> @yuzisun How did you generate the html for the API? Shame it misses listing the string types such as LoggerMode.
> /lgtm

Check the makefile recipe `make apidocs`, it is using the [crd api doc generator](https://github.com/ahmetb/gen-crd-api-reference-docs)

**Pull request merged**
