### PR TITLE
TF2OpenAPI: Complete openapi

### PR DESCRIPTION
**Pull request by jc2729**
**What this PR does / why we need it**: add JSON responses to OpenAPI

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/261)

### CODE REVIEW

**Comment by jc2729** [comment]
> Nice work!
> 
> I'm not a huge fan of what's going on with passing the Request objection 3 levels down through each layer of abstraction. Typically, when you see this type of code (i.e., a variable being passed 4 layers deep, where its only usage is at the bottom layer) it means that something hasn't been encapsulated correctly.
> 
> The way I think about it, you're somewhat abusing n-1 layer's of abstraction's function arguments for the purpose of the feature you're wiring through. If that feature you're wiring through is fundamental to all the layers, then its acceptable, otherwise, you're leaking encapsulation in multiple places.
> 
> I think the key problem is that our OpenAPI spec at the top level expects two schemas, and the way you've modeled this, is you've given the whole codebase a concept for the different schemas.
> 
> I've been trying to brainstorm another option, but it isn't super obvious to me. The best I've come up with is the following:
> 
> Change `model.Schema(g.metaGraphTags, g.sigDefKey, types.Request)` to return an OpenAPI Componen instead of an OpenAPI schema. This effectively makes our generator responsible for both the request and the response formats in all cases, instead of having the option of one or the other. You now can simply attach the content of the request/response at any level (I expect it will continue to happen at the bottom level with the row/col methods) and everything should wire up more cleanly.
> 
> What do you think?



> Nice work!
> 
> I'm not a huge fan of what's going on with passing the Request objection 3 levels down through each layer of abstraction. Typically, when you see this type of code (i.e., a variable being passed 4 layers deep, where its only usage is at the bottom layer) it means that something hasn't been encapsulated correctly.
> 
> The way I think about it, you're somewhat abusing n-1 layer's of abstraction's function arguments for the purpose of the feature you're wiring through. If that feature you're wiring through is fundamental to all the layers, then its acceptable, otherwise, you're leaking encapsulation in multiple places.
> 
> I think the key problem is that our OpenAPI spec at the top level expects two schemas, and the way you've modeled this, is you've given the whole codebase a concept for the different schemas.
> 
> I've been trying to brainstorm another option, but it isn't super obvious to me. The best I've come up with is the following:
> 
> Change `model.Schema(g.metaGraphTags, g.sigDefKey, types.Request)` to return an OpenAPI Componen instead of an OpenAPI schema. This effectively makes our generator responsible for both the request and the response formats in all cases, instead of having the option of one or the other. You now can simply attach the content of the request/response at any level (I expect it will continue to happen at the bottom level with the row/col methods) and everything should wire up more cleanly.
> 
> What do you think?

If I'm understanding correctly, I agree with the idea of limiting the notion of request/response options to the types package instead of exposing those options to the entire code base. 

Instead of having `model.Schema` return an entire OpenAPI Component, however, I think `model.Schema` could return two values, one request and one response schema. That way, `tfsavedmodel.go` in types won't be responsible for how the API is wired (i.e. how the components are laid out and component refs). 

Meanwhile, within the types package, Schema calls for `tfsavedmodel.go`, `tfmetagraph.go`, and `tfsignaturedef.go` would also return two values, one request and one response schema. Is that what you were suggesting?

**Comment by ellis-bigelow** [comment]
After discussing offline, it seems like component is the wrong abstraction. The middle ground you've found with multiple return types seems good to me!

**Pull request merged**
