### PR TITLE
Improve README

### LINKED ISSUE #1160: Moving presubmit jobs to Shared Test-infra (AWS CI)
Community is asking different WG to own their infra and community won't provide a GCP common shared testing infra anymore. Sees kubeflow/testing#752 for more details.

Katib and Pytorch migration works well and here's the PR to update test case to work on AWS Prow+ Argo cluster.
kubeflow/pytorch-operator#305

As we discussed offline, creating this issue to keep track migration work for kfserving. 

/cc @kubeflow/wg-serving-leads

### PR DESCRIPTION
**Pull request by PatrickXYS**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
2. Please **DO NOT MERGE UNTIL the prowjob on shared test-infra succeeds**

**Release note**:

```release-note
This PR is used to monitor if Presubmit Job for Kfserving on Shared Test-infra is set up well
```

### CODE REVIEW

**Comment by PatrickXYS** [comment]
The aws-kf-ci-bot is not yet synced with Kfserving repo write access

image

**Comment by PatrickXYS** [comment]
Tracking Permission Issue here

https://github.com/kubeflow/internal-acls/issues/361

**Comment by yuzisun** [comment]
this is taken care by https://github.com/kubeflow/kfserving/pull/1170 now.

/lgtm
/approve

**Pull request merged**
