### PR TITLE
vendor in istio types

### PR DESCRIPTION
**Pull request by rakelkar**
Required for #339 (breaking up into smaller commits)

The only change made here is:
```
dep ensure -add knative.dev/pkg/apis/istio/v1alpha3
```

/assign @yuzisun

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/373)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Just confirming you did this with dep ensure, right?

**Comment by rakelkar** [comment]
yas:
```
dep ensure -add knative.dev/pkg/apis/istio/v1alpha3
```

**Comment by rakelkar** [comment]
@yuzisun @ellis-bigelow can approve?

**Comment by yuzisun** [comment]
Looks good!
/lgtm
/approve

**Pull request merged**
