### PR TITLE
fix the wrong prebuild image address

### PR DESCRIPTION
**Pull request by edenbuaa**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
@edenbuaa Can you help sign the CLA?

**Comment by edenbuaa** [comment]
@googlebot I signed it!

**Comment by yuzisun** [comment]
Thanks for the fix! @edenbuaa 
/lgtm
/approve

**Pull request merged**
