### PR TITLE
Update the Dockerfile to support ppc64le.

### PR DESCRIPTION
**Pull request by alongzhi**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/348)

### CODE REVIEW

**Comment by jinchihe** [comment]
@alongzhi the test problem has been fixed in the #349, could you please rebase? Thanks.

**Comment by alongzhi** [comment]
@jinchihe thanks, retest passed.

**Pull request merged**
