### PR TITLE
Add sample deploying custom image using KFServing client sdk

### LINKED ISSUE #694: Improve custom image sample documentation.
/kind feature

Add an example using a prebuilt existing container with a model wrapped inside it. 

Add another example that extends the KFServing SDK to create a container compatible with KFServing client format, so that all the functionalities of KFServing can be leveraged

### PR DESCRIPTION
**Pull request by rzgry**
**What this PR does / why we need it**:
Updates the kfserving custom model sample to add instructions to deploy/run a prediction using either the command line or the python sdk.

**Which issue(s) this PR fixes**
Closes #694

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/723)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Please resolve the conflicts.

**Comment by rzgry** [comment]
@ellis-bigelow So right now everything in the `kfserving-custom-model/model-server` directory is just used to build the Docker image used in the sample. So the `requirements.txt` in that directory is just the minimum needed to build that custom model docker image that uses `kfserving.KFModel`.

Everything in the top level `kfserving-custom-model` dir is used to deploy that docker image to KFServing. With 2 options. 1. The command line using the custom.yaml file. Or 2. running a Jupyter notebook and using the KFServing client sdk (Which is what the other `requirements.txt`) is for.

Would you prefer just 1 `requirements.txt` that includes extra stuff like jupyter that will be added to the custom server docker image. Or use 2 files, one for the docker image that does not need to be installed by the user and is only used by the dockerfile, and another that is only installed if they want to deploy using jupyter and the kfserving client sdk?

**Comment by rzgry** [comment]
@ellis-bigelow any more thoughts on my comment above / directory structure?

**Comment by ellis-bigelow** [comment]
Looks great! Just a quick rebase and I'll approve.

**Comment by rzgry** [comment]
@ellis-bigelow done. let me know if I should change / update anything else.

**Comment by MATRIX4284** [comment]
This article explains how to deploy custom docker image in kfseving pytorch :

https://medium.com/@kaustavmukherjee_66179/serve-your-pytorch-models-on-cpu-or-nvidia-gpu-leveraging-kubeflow-kfserving-using-pytorch-server-d24725e779a0

**Comment by yuzisun** [comment]
@MATRIX4284 just read the article you wrote, we are working on v1beta1 api where you can specify the image directly without doing all these. Just curious in your case what you are customizing ?

**Comment by MATRIX4284** [comment]
Hi,

In the documentation of kf-serving pytorch serving it is not properly
mentioned where to provide the custom image name for the the pytorch.yaml
inference service that is located at the folder docs/samples/pytorch/.
Moreover my example also shows how to change the prediction service by
overloading the load and predict functions of model.py .being a Kubeflow
evangelist when i preach my customers about kfserving the pytorch server is
very tough to implement for a custom model thats why i provided an entire
list of commands needed to make the kf-serving pytorch server more useful.

*Cheers,*
*Kaustav*
*Technical Envagelist*
*Embedded & Distributed Systems*

**Comment by MATRIX4284** [comment]
Hi,

In case somebody uses the current version it will be helpful.i am also
adding how to change the pytorch serving code i.e. the model.py found in
/python/pytorchserver/pytorchserver by overloading the load() and predict()
functions to accommodate model copy from local filesystem and adding custom
transformation and data manipulation codes which the predict can call for a
complete data pipeline.I have my git ready and will publish soon.

*Thanks & Regards,*
*Kaustav*
*Technical Envagelist*
*Embedded & Distributed Systems*

**Comment by yuzisun** [comment]
@MATRIX4284 totally agree with you, we are well aware of this issue and in v1beta1 design you should be able to specify the custom image on pytorch spec if you are fulfilling the contract of KFServer. On the other hand have you looked at the [transformer](https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer) example to add the custom transformation ?

**Pull request merged**
