### PR TITLE
Fix link to inferenceservice configmap

### PR DESCRIPTION
**Pull request by markwinter**
**What this PR does / why we need it**:

Updates the link to the InferneceService configmap

### CODE REVIEW

**Comment by theofpa** [comment]
@markwinter thanks for the fix, I wonder how many other dead links we have in markdown files across the repo, is there a way to find out?
/lgtm

**Comment by yuzisun** [comment]
> @markwinter thanks for the fix, I wonder how many other dead links we have in markdown files across the repo, is there a way to find out?
> /lgtm

Is there any tools we can use to help check the deadlinks ?

**Comment by markwinter** [comment]
@theofpa @yuzisun 

I couldn't find anything with a quick search, so I made a python script

https://github.com/markwinter/find-dead-links

**Comment by theofpa** [comment]
that's awesome! I think these are the ones we need to fix:

```
$ python find_dead_links.py ../kfserving/
[*] Finding all .md pages
	[*] Found 190 pages
[*] Finding all links in pages
	[*] Found 1318 links
[*] Trying links
...
```
* Page: /ROADMAP.md, Link: ../kfserving////[prediction V2 API](https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2), Status: local file/dir not found
* Page: python/lgbserver/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/lightgbm, Status: HTTP 404
* Page: python/sklearnserver/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/sklearn, Status: HTTP 404
* Page: python/pmmlserver/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/pmml, Status: HTTP 429
* Page: python/pytorchserver/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/pytorch, Status: HTTP 429
* Page: docs/MULTIMODELSERVING_GUIDE.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/triton/multimodel, Status: HTTP 404
* Page: docs/MULTIMODELSERVING_GUIDE.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/sklearn/multimodel, Status: HTTP 404
* Page: docs/README.md, Link: ../kfserving//docs//docs/predict-api/v2, Status: local file/dir not found
* Page: docs/samples/README.md, Link: ../kfserving//docs/samples/./v1beta1/v2/sklearn, Status: local file/dir not found
* Page: docs/samples/README.md, Link: ../kfserving//docs/samples/./v1beta1/v1/sklearn, Status: local file/dir not found
* Page: docs/samples/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/python/lightgbm, Status: HTTP 404
* Page: docs/samples/gcp-iap/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/sklearn, Status: HTTP 404
* Page: docs/samples/istio-dex/README.md, Link: ../kfserving//docs/samples/istio-dex/../sklearn, Status: local file/dir not found
* Page: docs/samples/v1alpha2/pytorch/README.md, Link: ../kfserving//docs/samples/v1alpha2/pytorch/../../../python/pytorchserver, Status: local file/dir not found
* Page: docs/samples/v1alpha2/sklearn/README.md, Link: ../kfserving//docs/samples/v1alpha2/sklearn/../../../python/sklearnserver, Status: local file/dir not found
* Page: docs/samples/v1alpha2/sklearn/README.md, Link: ../kfserving//docs/samples/v1alpha2/sklearn/../../../python/sklearnserver/README.md, Status: local file/dir not found
* Page: docs/samples/v1alpha2/sklearn/README.md, Link: ../kfserving//docs/samples/v1alpha2/sklearn/../../../config/configmap/inferenceservice.yaml, Status: local file/dir not found
* Page: docs/samples/v1alpha2/xgboost/README.md, Link: ../kfserving//docs/samples/v1alpha2/xgboost/../../../python/xgbserver, Status: local file/dir not found
* Page: docs/samples/v1alpha2/xgboost/README.md, Link: ../kfserving//docs/samples/v1alpha2/xgboost/../../../python/xgbserver/README.md, Status: local file/dir not found
* Page: docs/samples/v1alpha2/xgboost/README.md, Link: ../kfserving//docs/samples/v1alpha2/xgboost/../../../config/configmap/inferenceservice.yaml, Status: local file/dir not found
* Page: docs/samples/v1beta1/lightgbm/README.md, Link: ../kfserving//docs/samples/v1beta1/lightgbm/../../../python/lgbserver/README.md, Status: local file/dir not found
* Page: docs/samples/v1beta1/triton/torchscript/README.md, Link: ../kfserving//docs/samples/v1beta1/triton/torchscript/../eager/cifar10.py, Status: local file/dir not found
* Page: docs/samples/v1beta1/torchserve/README.md, Link: ../kfserving//docs/samples/v1beta1/torchserve/../imgconv/README.md, Status: local file/dir not found
* Page: docs/samples/v1beta1/sklearn/v1/README.md, Link: ../kfserving//docs/samples/v1beta1/sklearn/v1/../../../python/sklearnserver, Status: local file/dir not found
* Page: docs/samples/v1beta1/sklearn/v1/README.md, Link: ../kfserving//docs/samples/v1beta1/sklearn/v1/../../../python/sklearnserver/README.md, Status: local file/dir not found
* Page: docs/samples/v1beta1/sklearn/v1/README.md, Link: ../kfserving//docs/samples/v1beta1/sklearn/v1/../../../config/configmap/inferenceservice.yaml, Status: local file/dir not found
* Page: docs/samples/v1beta1/sklearn/v2/README.md, Link: ../kfserving//docs/samples/v1beta1/sklearn/v2/../../../predict-api/v2, Status: local file/dir not found
* Page: docs/samples/v1beta1/sklearn/v2/README.md, Link: ../kfserving//docs/samples/v1beta1/sklearn/v2/../../../predict-api/v2, Status: local file/dir not found
* Page: docs/samples/explanation/alibi/moviesentiment/README.md, Link: ../kfserving//docs/samples/explanation/alibi/moviesentiment/./kfserving_text_explainer.ipynb, Status: local file/dir not found
* Page: docs/samples/explanation/aix/mnist/README.md, Link: ../kfserving//docs/samples/explanation/aix/mnist//python/aixexplainer, Status: local file/dir not found
* Page: docs/samples/explanation/art/mnist/README.md, Link: ../kfserving//docs/samples/explanation/art/mnist//python/artexplainer, Status: local file/dir not found
* Page: docs/samples/custom-domain/README.md, Link: https://github.com/kubeflow/kfserving/tree/master/docs/samples/sklearn, Status: HTTP 404
* Page: test/scripts/linux-amd64/README.md, Link: ../kfserving//test/scripts/linux-amd64/code-of-conduct.md, Status: local file/dir not found

**Pull request merged**
