### PR TITLE
use "kustomize build" instead of "kubectl kustomize"

### PR DESCRIPTION
**Pull request by jazzsir**
**What this PR does / why we need it**:
We use "kustomize build" instead of "kubectl kustomize" to avoid many changes.
To use existing one, some keyword should be changed for compatibility.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by pugangxa** [comment]
When I run ```kustomize build``` it reports: 
```
Error: json: unknown field "env"
```
So I also did the changes in this PR and it passed. 

But there's other issues(see issue #1127 ) . 
And also I found this https://github.com/kubernetes-sigs/kustomize/issues/2052 and seems it's not recommended to use vars. So maybe we should revert PR #1103 )?
@yuzisun

**Comment by yuzisun** [comment]
> When I run `kustomize build` it reports:
> 
> ```
> Error: json: unknown field "env"
> ```
> 
> So I also did the changes in this PR and it passed.
> 
> But there's other issues(see issue #1127 ) .
> And also I found this [kubernetes-sigs/kustomize#2052](https://github.com/kubernetes-sigs/kustomize/issues/2052) and seems it's not recommended to use vars. So maybe we should revert PR #1103 )?
> @yuzisun

I think @jazzsir borrowed this from kubeflow manifests, will read a bit why vars are not recommended. But I do not see the issue reported in #1127, is that kustomize version issue ?

**Comment by yuzisun** [comment]
@pugangxa i think this is ok and it is passing the CI, pretty sure the CI does kustomize build and the conversion also.

/lgtm
/approve

**Pull request merged**
