### PR TITLE
Add pytorch GPU image for inference

### LINKED ISSUE #537: Create PyTorch GPU Image for GPU inference
/kind feature

**Describe the solution you'd like**
For PyTorch GPU inference we need to create an image with `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04` as base image  and `Apex` which is pytorch extension with NVIDIA-maintained utilities to streamline mixed precision and distributed training. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:
Add Pytorch GPU image for inference on GPUs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #537 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/540)

### CODE REVIEW

**Comment by cliveseldon** [comment]
Great you added the simpletransformers library.

**Comment by yuzisun** [comment]
> Great you added the simpletransformers library.

I did !

**Comment by yuzisun** [comment]
@alexwennerberg I have tested this, it is good to go.

**Comment by ellis-bigelow** [comment]
@yuzisun can I ask you to implement an e2e test to make sure we don't regress on this feature in the future?

**Comment by yuzisun** [comment]
Is it possible to create the test cluster with gpu ?

**Comment by florian-koenig** [comment]
Any indication of when we can expect a release with this change? Without GPU support we can't continue our migration to kfserving.

**Comment by ellis-bigelow** [comment]
Looks like this fails the pytorch e2e test.

**Comment by yuzisun** [comment]
> Looks like this fails the pytorch e2e test.

@ellis-bigelow this is good to go we have gpu e2e test now! it was getting OOM :)

**Comment by ellis-bigelow** [comment]
Awesome thank you!

**Comment by florian-koenig** [comment]
Thank you for taking care of this! We are very happy to see this moving forward. Can't wait to give it a try.

**Pull request merged**
