### PR TITLE
Remove redundant code in ONNX InferenceService sample

### PR DESCRIPTION
**Pull request by nuka137**
**What this PR does / why we need it**:

Remove redundant code in ONNX InferenceService sample notebook.
Some modules are imported in multiple times.

### CODE REVIEW

**Comment by adriangonz** [comment]
Hey @nuka137, aren't those imports used down the line within the same notebook?

**Comment by nuka137** [comment]
@adriangonz 

Yes, that's right.
But, these import lines also exist in third code block.

```python
from PIL import Image
import numpy as np
import google.protobuf.json_format as json_format
import assets.onnx_ml_pb2 as onnx_ml_pb2
import assets.predict_pb2 as predict_pb2
import requests
```

So, I think we can remove redundant import lines.

**Comment by nuka137** [comment]
@adriangonz 

> But, these import lines also exist in third code block.
> So, I think we can remove redundant import lines.

Is there any comments about my idea?

**Comment by adriangonz** [comment]
Good spot @nuka137 ! Looking good from my side, although there seems to be a failing test. I've kicked it off again. If it passes, this looks good from my side.

/test kubeflow-kfserving-presubmit

**Pull request merged**
