### PR TITLE
Add pugangxa as reviewer

### PR DESCRIPTION
**Pull request by pugangxa**
**What this PR does / why we need it**:

Would you please add me as reviewer? 
Now some PR about validation, logger, testing and development story enhancement... And would like to do more.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/661)

### CODE REVIEW

**Comment by jinchihe** [comment]
/lgtm

Gang contributed great features and fixed some bugs of kfserving. Thanks Gang!
/cc @ellis-bigelow @animeshsingh

**Comment by ellis-bigelow** [comment]
Sounds good to me! 3 lgtms should be good (Dan, Animesh and I).
/lgtm
@animeshsingh to approve.

**Pull request merged**
