### PR TITLE
ML Serving Spec Review

### PR DESCRIPTION
**Pull request by animeshsingh**
Hi - we have a strong interest in shaping this up, and have worked with Seldon in the past as well. Would like to be added as a reviewer to help shape this up and also bring some use cases from IBM perspective

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/4)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Hey Animesh,
Let's chat in Kubeflow Slack when you get a chance.

**Comment by ellis-bigelow** [comment]
@animeshsingh, FYI we have a weekly meeting on Wednesdays at 9am. Ping me your email address at ellisbigelow@google.com and I'll add you.

**Comment by gaocegege** [comment]
Please solve the conflicts, thanks

**Comment by animeshsingh** [comment]
closing this and resbmitting - seems some issue

**Pull request closed without merging**
