### PR TITLE
Add support for local file

### PR DESCRIPTION
**Pull request by aurorazl**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Add support for localfile when storageUri like file://,
```

### CODE REVIEW

**Comment by ellistarn** [comment]
We're not actively supporting this Alpha branch. Do you mind detailing why you need this?

**Comment by aurorazl** [comment]
> We're not actively supporting this Alpha branch. Do you mind detailing why you need this?

The change can apply to master branch! It can be used for supporting localfile like "file://path".

**Comment by yuzisun** [comment]
> > We're not actively supporting this Alpha branch. Do you mind detailing why you need this?
> 
> The change can apply to master branch! It can be used for supporting localfile like "file://path".

@aurorazl what's the use case for local file path? KFserving already supports pvc

**Comment by pugangxa** [comment]
Yes it's not work in my test, and I once submitted a PR ([#622](https://github.com/kubeflow/kfserving/pull/622)) to remove it. I think there should not be use case for this and the only thing I can think about is for local testing.

**Comment by yuzisun** [comment]
closing staled PR

**Pull request closed without merging**
