### PR TITLE
Add Qingshan Chen from Inspur as a reviewer

### PR DESCRIPTION
**Pull request by animeshsingh**
additionally remove some inactive reviewers

### CODE REVIEW

**Comment by animeshsingh** [comment]
@Iamlovingit can you lgtm this
https://github.com/kubeflow/internal-acls/pull/293

also the current PR in KFServing

**Comment by Iamlovingit** [comment]
lgtm

**Comment by ellistarn** [comment]
@Iamlovingit thanks for your contributions!

**Comment by animeshsingh** [comment]
@Iamlovingit you should have gotten a request to join the Kubeflow github org. Please accept and letme know

**Comment by Iamlovingit** [comment]
@animeshsingh I have accepted the request, thanks.

**Pull request merged**
