### PR TITLE
WIP: upgrade code gen which is subtask to upgrade to knative v0.10

### LINKED ISSUE #596: Upgrading KFServing to KNative 0.11
/kind feature

**Describe the solution you'd like**
KFServing needs to be upgraded to KNative 0.10 for getting the latest enhancements around cold starts, caching etc.

This requires a chain of cascading dependencies.

KNative 0.10 takes a dependency on Kube 1.15.3 APIs . Best is to revisit this from backwards now, first migrating KFServing dependencies to Kube 1.14+ APIs et all before visiting KNative 0.10. We can follow a more sequential approach

1. openapi code gen for 1.14 and 1.15 has migrated to another pkg (k8s.io/kube-openapi/cmd/openapi-gen) which causes some compatibility issues with k8s 1.15.3. 
@pugangxa @jinchihe 

2. We also need to update the code gen config since the new code gen now is doing some API naming check by default (e.g. the API rule violation).  Unit tests may also need to be migrated to the new rules. Code gen files that need additional flags:
https://github.com/kubeflow/kfserving/blob/master/hack/update-codegen.sh
https://github.com/kubeflow/kfserving/blob/master/hack/update-openapigen.sh

API names match rule: 
https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/rules/names_match.go#L54-L76

e.g. According to the new name matching, StorageURI in json should be storageURI (not storageUri), so we may want to ignore some rule checking or update all our current API naming and bump it to a new api version.

 @pugangxa @jinchihe 

3. controller-runtime and controller-tools need to migrate to a version where the admission webhook type pkg is deprecated. We need to figure out which pkg we should migrate to the new version and use the new webhook implementation.
@hougangliu 

4. There are also few type changes that get introduced in 1.14 and 1.15 that we need to fix. Unfortunately I can’t get to this part yet so I can’t estimate how much effort it will need. k8s.io vendor libraries need to be migrated to Kube 1.15.3
@hougangliu 

5. Knative APIs need to be migrated to V1 from V1alpha1
@Tomcli 

6. KNative libraries need to be upgraded to 0.10
@animeshsingh

### PR DESCRIPTION
**Pull request by pugangxa**
**What this PR does / why we need it**:
This is subtask to upgrade to knative v0.10

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #596 item 2

**Special notes for your reviewer**:
- This should be merged after PR #600 so I commented out the openapi generation in Makefile
- Now the client can be generated but during build there's error like below:
```
➜  kfserving git:(upgrade-code-gen) make manager
go generate ./pkg/... ./cmd/...
hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/clientset
Generating listers for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/listers
Generating informers for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/informers
#hack/update-openapigen.sh
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
# github.com/kubeflow/kfserving/pkg/client/clientset/versioned/typed/serving/v1alpha2
pkg/client/clientset/versioned/typed/serving/v1alpha2/serving_client.go:73:45: "github.com/kubeflow/kfserving/pkg/client/clientset/versioned/scheme".Codecs.WithoutConversion undefined (type serializer.CodecFactory has no field or method WithoutConversion)
make: *** [vet] Error 2
```
@animeshsingh This error is due to the version of k8s.io/apimachinery which is still at "kubernetes-1.12.6". Do you have a plan to commit other upgrading parts firstly? I'm afraid these changes need be go together to pass all the testing.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/601)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@pugangxa kube upgrade to 1.15.3 is part of @hougangliu charter. If you can discuss with him - and include in your PR if its needed

**Comment by jinchihe** [comment]
Thanks for taking this. @Gang

**Comment by animeshsingh** [comment]
Adding, this is handling a work item in the overall KNative 0.10 migration
https://github.com/kubeflow/kfserving/issues/596

**Comment by yuzisun** [comment]
@pugangxa I have consolidated your PR and animesh’s one onto https://github.com/kubeflow/kfserving/pull/630, there a lot of other stuff I changed to pass the CI. You can close this one, all the changes here are token care, thanks !

**Comment by pugangxa** [comment]
> @pugangxa I have consolidated your PR and animesh’s one onto #630, there a lot of other stuff I changed to pass the CI. You can close this one, all the changes here are token care, thanks !

Thanks, close this one.

**Pull request closed without merging**
