### PR TITLE
Upgrade KFService to use Knative Serving v1beta1 API

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:
- update KFService to use knative serving v1beta1 API
- set knative defaults to avoid diffs which causes unnecessary updates and unhappy logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubeflow/kfserving/issues/190

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
KFService now starts to create Knative v1beta1 resources
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/382)

### CODE REVIEW

**Comment by johnugeorge** [comment]
LGTM

@yuzisun  
One comment: 
I see that default installation of Knative still points to v1alpha1 version of APIs.  See: https://knative.dev/docs/install/knative-custom-install/  and corresponding serving yaml - https://github.com/knative/serving/releases/download/v0.9.0/serving.yaml   

Also, Upgrade story to v1beta1 will have problems for pre 1.14 clusters.  They might to have to re-install knative with v1beta1 crds on pre 1.14 clusters. 

We didn't upgrade to v1beta1 version earlier because of the same reason.  WDYT?

**Comment by yuzisun** [comment]
@johnugeorge considering kubernetes 1.15 is out and most of users should have already adopted Kubernetes 1.14 so far, so it is ok to go v1beta1 and document the requirement that KFServing needs 1.14+ ? I'd like to get v1beta1 since it allows multiple containers on podsec so we no longer need to use mutation webhook to inject the storage initializer.

**Comment by johnugeorge** [comment]
Sounds good. Then only thing that is left is, We have to add the requirement to readme to specifically install post 1.14 yaml which contains v1beta1 crds.  (As the default contains v1alpha1)

**Pull request closed without merging**
