### PR TITLE
Update Knative Serving API version from v1alpha1 to v1

### LINKED ISSUE #574: Migrate knative crd from v1alpha1 to v1
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
With #543, we will migrate to Knative 0.9 which supports the latest Knative v1 api. Since we are still using the v1alpha1 Knative crd, we should consider migrating it to the v1 api before Knative v1alpha1 deprecated in the future version. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Tomcli**
**What this PR does / why we need it**:
Fixing #574 by migrating Knative Serving to use the latest v1 api. Note that the knative v1 api only available from Knative 0.9+. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #574 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
### Moving minimum Knative Serving Version to v0.9.0
As part of moving the Knative API to v1 we are moving the minimum supported Knative version to 0.9.0
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/585)

### CODE REVIEW

**Comment by Tomcli** [comment]
/hold
Sorry looks like the v1 crd for serving is coming by default on Knative 0.10. On 0.9 the default only has v1alpha1, so we need to deploy with the [serving-v1-crd.yaml](https://github.com/knative/serving/releases/download/v0.9.0/serving-v1-crds.yaml) . We can hold this until we migrate to knative 0.10.

**Comment by yuzisun** [comment]
> /hold
> Sorry looks like the v1 crd for serving is coming by default on Knative 0.10. On 0.9 the default only has v1alpha1, so we need to deploy with the [serving-v1-crd.yaml](https://github.com/knative/serving/releases/download/v0.9.0/serving-v1-crds.yaml) . We can hold this until we migrate to knative 0.10.

knative 0.10.0 upgrade PR in manfests https://github.com/kubeflow/manifests/pull/651

**Comment by Tomcli** [comment]
This package we refer in the sdk test is returning 404.
http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages

**Comment by yuzisun** [comment]
I think this can get in first, I tested it works with 0.9 too you just need to install v1 crd.

**Comment by Tomcli** [comment]
Thanks @yuzisun, I merged with the latest master to make sure all the tests are passed now. 
/unhold

**Comment by animeshsingh** [comment]
I would prefer keeping it on hold for a while until we get it by default. 
"you just need to install v1 crd." - 0.9 is a transient stop at this point.-  a point in time step which can be negated with 0.10 move, so best to get it in with that, or we need to explicitly add instructions to install this crd.

**Comment by yuzisun** [comment]
> I would prefer keeping it on hold for a while until we get it by default.
> "you just need to install v1 crd." - 0.9 is a transient stop at this point.- a point in time step which can be negated with 0.10 move, so best to get it in with that, or we need to explicitly add instructions to install this crd.

understood, I just do not want these PRs hanging there for long and get staled. How far are we with the other 0.10 PRs ?

**Comment by Tomcli** [comment]
ok I can keep it on hold until Knative 0.10 is ready.
/hold

**Comment by animeshsingh** [comment]
Will be tracking it here. Will get the latest on all tonight. 1,2 and 5 are looking good for the moment. 
https://github.com/kubeflow/kfserving/issues/596

**Comment by yuzisun** [comment]
@animeshsingh @Tomcli We can unhold this one now, let's merge this first and then https://github.com/kubeflow/kfserving/pull/630

**Comment by Tomcli** [comment]
Thanks @yuzisun 
/unhold

**Comment by Tomcli** [comment]
unit test timed out
/retest

**Pull request merged**
