### PR TITLE
bump e2e tests to k8s-1.19, istio-1.8.2, knative-0.21

### PR DESCRIPTION
**Pull request by theofpa**
**What this PR does / why we need it**:
Following up on the WG discussion, bumping the versions of k8s/istio/knative in the e2e-test to:
* k8s-1.19
* istio-1.8.2
* knative-0.21

Tested with `make deploy-dev` locally.

### CODE REVIEW

**Comment by theofpa** [comment]
we need to bump eksctl in kubeflow/testing
```
(base) theofpa@z420:~$ k logs kubeflow-kfserving-presubmit-e2e-1482-d9a0c57-0320-7587-2364830325 -c main
Starting to create eks cluster
[ℹ]  eksctl version 0.30.0
[ℹ]  using region us-west-2
Error: invalid version, supported values: 1.14, 1.15, 1.16, 1.17, 1.18
```

**Comment by yuzisun** [comment]
Thanks @theofpa !
/lgtm
/approve

**Pull request merged**
