### PR TITLE
Cherry-pick of 'Support Kubernetes 1.18' (#1128) to release-0.4

### PR DESCRIPTION
**Pull request by pvaneck**
This PR cherrypicks a yaml fix commit (#1128). This is a yaml only change.

### CODE REVIEW

**Comment by pugangxa** [comment]
@googlebot I consent.

**Comment by yuzisun** [comment]
looks like test volume is busted
```
fatal: could not create leading directories of '/mnt/test-data-volume/kubeflow-kfserving-presubmit-e2e-1169-12be87a-3728-c6b0/src/kubeflow/kfserving': No space le
ft on device
```

**Comment by yuzisun** [comment]
looks like related to this issue https://github.com/kubeflow/testing/issues/769 ?

**Comment by yuzisun** [comment]
I am merging this manually while we are porting over CI to AWS

**Pull request merged**
