### PR TITLE
Enabled test_sklearn.py, etc. to run in an env without ext load balancer

### PR DESCRIPTION
**Pull request by janeman98**
**What this PR does / why we need it**:
Currently, when running test_sklearn.py, test_tensorflow.py, test_xgboost.py, test_transformer.py in an environment without ext loadbalancer, it fails with :

_>       cluster_ip = service.status.load_balancer.ingress[0].ip
E       TypeError: 'NoneType' object is not subscriptable_

[As load balancer is not required](https://github.com/kubeflow/kfserving/issues/629#issuecomment-578401707), will use this PR to enable these to run in an environment w/o ext loadbalancer.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/649)

### CODE REVIEW

**Comment by janeman98** [comment]
The presubmit test failed in

_--- FAIL: TestInferenceServiceWithOnlyPredictor
VirtualService.networking.istio.io "foo" not found_

Will look further into it.

**Comment by yuzisun** [comment]
> The presubmit test failed in
> 
> _--- FAIL: TestInferenceServiceWithOnlyPredictor VirtualService.networking.istio.io "foo" not found_
> 
> Will look further into it.

Can you run locally to see if can be reproduced ?

**Comment by janeman98** [comment]
> > The presubmit test failed in
> > _--- FAIL: TestInferenceServiceWithOnlyPredictor VirtualService.networking.istio.io "foo" not found_
> > Will look further into it.
> 
> Can you run locally to see if can be reproduced ?

Don't see such error when run locally (use make test):

`(base) root@jane91:~/go/src/github.com/kubeflow/kfserving# make test
go generate ./pkg/... ./cmd/...
hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/clientset
Generating listers for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/listers
Generating informers for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/informers
hack/update-openapigen.sh
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
hack/verify-golint.sh
Congratulations!  All Go source files have been linted.
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go "crd:trivialVersions=true" rbac:roleName=kfserving-manager-role webhook paths=./pkg/apis/... output:crd:dir=config/default/crds/base
kustomize build config/default/crds -o config/default/crds/base/serving.kubeflow.org_inferenceservices.yaml
go test ./pkg/... ./cmd/... -coverprofile cover.out
?       github.com/kubeflow/kfserving/pkg/apis  [no test files]
?       github.com/kubeflow/kfserving/pkg/apis/serving  [no test files]
ok      github.com/kubeflow/kfserving/pkg/apis/serving/v1alpha2 15.084s coverage: 53.4% of statements
?       github.com/kubeflow/kfserving/pkg/client/clientset/versioned    [no test files]
?       github.com/kubeflow/kfserving/pkg/client/clientset/versioned/fake  [no test files]
?       github.com/kubeflow/kfserving/pkg/client/clientset/versioned/scheme                                                                 [no test files]
?       github.com/kubeflow/kfserving/pkg/client/clientset/versioned/typed/serving/v1alpha2                                                 [no test files]
?       github.com/kubeflow/kfserving/pkg/client/clientset/versioned/typed/serving/v1alpha2/fake                                            [no test files]
?       github.com/kubeflow/kfserving/pkg/client/informers/externalversions                                                                 [no test files]
?       github.com/kubeflow/kfserving/pkg/client/informers/externalversions/internalinterfaces                                              [no test files]
?       github.com/kubeflow/kfserving/pkg/client/informers/externalversions/serving                                                         [no test files]
?       github.com/kubeflow/kfserving/pkg/client/informers/externalversions/serving/v1alpha2                                                [no test files]
?       github.com/kubeflow/kfserving/pkg/client/listers/serving/v1alpha2  [no test files]
?       github.com/kubeflow/kfserving/pkg/constants     [no test files]
?       github.com/kubeflow/kfserving/pkg/controller    [no test files]
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice   19.167s                                                             coverage: 73.3% of statements
?       github.com/kubeflow/kfserving/pkg/controller/inferenceservice/reconcilers/istio                                                     [no test files]
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/reconcilers/knative                                                   14.353s  coverage: 66.7% of statements
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials                                                 18.222s  coverage: 83.3% of statements
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials/azure                                           0.526s   coverage: 100.0% of statements
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials/gcs                                             0.292s   coverage: 100.0% of statements
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials/s3                                              0.512s   coverage: 96.3% of statements
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/istio                                                       1.481s   coverage: 84.0% of statements
ok      github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/knative                                                     14.075s  coverage: 51.1% of statements
ok      github.com/kubeflow/kfserving/pkg/logger        0.897s  coverage: 38.8% of statements
?       github.com/kubeflow/kfserving/pkg/testing       [no test files]
ok      github.com/kubeflow/kfserving/pkg/utils 0.083s  coverage: 100.0% of statements
?       github.com/kubeflow/kfserving/pkg/webhook/admission/inferenceservice                                                                [no test files]
ok      github.com/kubeflow/kfserving/pkg/webhook/admission/pod 12.746s coverage: 47.4% of statements
?       github.com/kubeflow/kfserving/cmd/logger        [no test files]
?       github.com/kubeflow/kfserving/cmd/manager       [no test files]
?       github.com/kubeflow/kfserving/cmd/spec-gen      [no test files]
(base) root@jane91:~/go/src/github.com/kubeflow/kfserving#`

**Comment by janeman98** [comment]
For some unknown reason, the logs from previous presubmit is gone.
/retest

**Comment by janeman98** [comment]
Many thanks, @yuzisun !

**Pull request merged**
