### PR TITLE
Adds Adopters.MD, adding Halodoc ID to the list

### PR DESCRIPTION
**Pull request by joinal-ahmed**
**What this PR does / why we need it**:
Adds Halodoc ID to adpoters.md
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: None

**Release note**:
NONE

### CODE REVIEW

**Review by animeshsingh — COMMENTED** [review]
/lgtm
/approve

**Comment by yuzisun** [comment]
@joinal-ahmed Can you help sign the CLA?

**Comment by joinal-ahmed** [comment]
@yuzisun should be okay

**Comment by yuzisun** [comment]
@joinal-ahmed looks like the CLA is still complaining.

```
Individual signers
It's possible we don't have your GitHub username or you're using a different email address on your commit. Check your existing CLA data and verify that your email is set on your git commits.
```

**Pull request merged**
