### PR TITLE
fix route and configuration race

### PR DESCRIPTION
**Pull request by rakelkar**
**What this PR does / why we need it**:
Fixes https://github.com/knative/serving/issues/4564

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/202)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Lol. How on earth does this help?

**Comment by ellis-bigelow** [comment]
Oh I just read the bug. Hilarious

**Comment by yuzisun** [comment]
haha, good finding!

**Pull request merged**
