### PR TITLE
Upgrade Feast transformer for v0.12.1

### PR DESCRIPTION
**Pull request by chinhuang007**
Made the following changes for Feast transformer to support the
latest Feast v0.12.1
1. Change the python client API to rest API
2. Use the new Feast feature server
3. Use python 3.8
4. Update sample outputs in doc

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
hi @chinhuang007! thanks for the PR, please kindly help move this PR to https://github.com/kserve/kserve

**Comment by chinhuang007** [comment]
@yuzisun Thanks for the review and comments! I will move this PR to kserve repo shortly.

**Pull request merged**
