### PR TITLE
[WIP] Renamed KFService to InferenceService

### LINKED ISSUE #317: Discuss: Rename KFService to MLService
We've discussed this idea before, opening an issue to discuss in the context of v1alpha2.

### Rationale:
KFServing as it currently stands defines an API spec and an implementation for serving. The spec models the ML domain but is not dependent on Kubeflow in any way. MLServing is a clearer name that reinforces the loose coupling of the API. 

wdyt?

### PR DESCRIPTION
**Pull request by ellis-bigelow**
**What this PR does / why we need it**:
Renames KFService to InferenceService. This spawned from the discussions in Working Groups and  https://github.com/kubeflow/kfserving/issues/317
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #317

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Renamed KFService to InferenceService to support generic interface adoption by the wider community.
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/385)

### CODE REVIEW

**Comment by aronchick** [comment]
Quick question - how hard is it to later change "*.serving.kubeflow.org" to something else? I think we'd want to change this _too_ but I don't know what we'd change it to.

**Comment by animeshsingh** [comment]
@ellis-bigelow this is  a post v0.2 change now? Possibly in a patch?

**Comment by ellis-bigelow** [comment]
You're right. I need to get this change in.

**Pull request closed without merging**
