### PR TITLE
Upgrade knative to v0.10.0 in CI tests

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

As required in https://github.com/kubeflow/kfserving/pull/586, u pgrade knative to v0.10.0 in CI tests.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/587)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@jinchihe I assume test wouldn't pass in this case?

**Comment by jinchihe** [comment]
/retest

Not sure, may be better to update CI testing with knative upgrading ticket, let me retest and check logs.

**Comment by jinchihe** [comment]
```
Unable to retrieve container logs for docker://78639975b83fc30b549b36beb076d97b9407764c459c656cc0b0f3882d5ab77e
```

/retest

**Comment by jinchihe** [comment]
Failed to install knative, I'm going to take a look.
```
error: error validating "https://github.com/knative/serving/releases/download/v0.10.0/serving.yaml": error validating data: ValidationErr
or(MutatingWebhookConfiguration.webhooks[0]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook
; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by animeshsingh** [comment]
any luck @jinchihe ? btw Istio has to be 1.3.1

**Comment by jinchihe** [comment]
@animeshsingh OK, will take high priority for this, thanks.

**Comment by jinchihe** [comment]
Goooood! Passed.

@animeshsingh @yuzisun That's ready to go. thanks.

**Comment by animeshsingh** [comment]
thanks @jinchihe - awesome!

/lgtm

**Pull request merged**
