### PR TITLE
WIP: Upgrading to KNative 0.10 

### PR DESCRIPTION
**Pull request by animeshsingh**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/586)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@jinchihe would be good to get a PR in the works for migrating test-infra to knative 0.10

**Comment by jinchihe** [comment]
@animeshsingh You may need to run `dep ensure` to involve new pacakges to pass unit tests, thanks.

**Comment by animeshsingh** [comment]
@jinchihe yup - this one is in some dependency jail - and requires a major overhaul, since knative 0.10 brings other dependencies along with it, which change the core of kube libraries kfserving has been on

**Comment by yuzisun** [comment]
@animeshsingh my PR is in here https://github.com/kubeflow/kfserving/pull/630, you can close this one now.

**Comment by animeshsingh** [comment]
thanks  -  closing this

**Pull request closed without merging**
