### PR TITLE
Upgrade controller-runtime to v0.7.0

### LINKED ISSUE #1307: Replace deprecated controller-runtime packages
/kind feature

**Describe the solution you'd like**
We use `controller-runtime/pkg/runtime/log` and `controller-runtime/pkg/runtime/signals` in a bunch of places. Both of these are deprecated and were deleted in v0.7.0 of `controller-runtime`:
https://github.com/kubernetes-sigs/controller-runtime/commit/a32b29d13265e87521ead29bed96d7fb44f57e1e#diff-c4abdec7bd505d8a03b365a244374fd9cde3fd5b69976d463896b3d1c171772d
https://github.com/kubernetes-sigs/controller-runtime/commit/34eb1151fa01429133100ea94a240344aaf96adc#diff-c4abdec7bd505d8a03b365a244374fd9cde3fd5b69976d463896b3d1c171772d

We should replace them with something else. This will allow us to either update the version of our `controller-runtime` dependency or get rid of it entirely. 

**Anything else you would like to add:**
More context - https://github.com/kubeflow/kfserving/pull/1305#discussion_r559771345

### PR DESCRIPTION
**Pull request by pugangxa**
**What this PR does / why we need it**:
Upgrade controller-runtime to v0.7.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1307 

**Special notes for your reviewer**:
This should be merged after PR #1305 to use k8s.io/api v0.19.2, or it will be build error.

### CODE REVIEW

**Comment by pugangxa** [comment]
How to rerun the AIXExplainer test and Python package test? Seems it's environment issues.

**Comment by yuzisun** [comment]
thanks @pugangxa !
/approve

**Pull request merged**
