### PR TITLE
Cutting v0.3.0 release

### PR DESCRIPTION
**Pull request by ellis-bigelow**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/700)

### CODE REVIEW

**Comment by jinchihe** [comment]
@ellis-bigelow I noticed you also updated the SDK version, that's great. Just confirm, will you release SDK 0.3 in Pypi  or need me to refresh that in Pypi? Thanks.

**Comment by ellis-bigelow** [comment]
> @ellis-bigelow I noticed you also updated the SDK version, that's great. Just confirm, will you release SDK 0.3 in Pypi or need me to refresh that in Pypi? Thanks.

I'm planning on doing the refresh as soon as this release is cut. At the same time I add the git tag. Alternatively, you could do it, which would be quite helpful!

**Comment by jinchihe** [comment]
> Alternatively, you could do it, which would be quite helpful!

@ellis-bigelow OK, I will refresh the SDK package in Pypi once the PR merged. Thanks.
/cc @animeshsingh

**Pull request merged**
