### PR TITLE
Cherry-pick of OpenShift fixes (#1122 and #1134) to release-0.4

### PR DESCRIPTION
**Pull request by pvaneck**
**What this PR does / why we need it**:
This PR cherrypicks two OpenShift fix commits (#1122 and #1134) in preparation for minor release (0.4.1).

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by pvaneck** [comment]
@pugangxa Had to resolve some conflicts in your commit while cherry-picking, so it looks like I need a `@googlebot I consent` message from you.

**Comment by pugangxa** [comment]
> pugangxa Had to resolve some conflicts in your commit while cherry-picking, so it looks like I need a `@googlebot I consent` message from you.

What does that mean and is there action needed from my side? To be honest I don't know how to help this out for you...

**Comment by pugangxa** [comment]
@googlebot I consent.

**Comment by pvaneck** [comment]
@pugangxa Thanks! Sorry, was confused by the google-cla bot's message, and just needed that message to stop it from complaining.

Also, test failures are due to some of the requirements for kfserving being too low causing import errors (`ImportError: cannot import name 'collections_abc'`). This was fixed in #1055.

**Review by animeshsingh — APPROVED** [review]
/lgtm

**Comment by animeshsingh** [comment]
@yuzisun should we just merge it, and cut a release, or you have something else in mind?

**Comment by yuzisun** [comment]
@animeshsingh let me cherry pick the kfserving sdk python dependency fix as well, that's breaking KFS 0.4 SDK due to some upstream gcloud storage library change.

**Comment by yuzisun** [comment]
@pvaneck can you help rebase release-0.4 for the dependency fix ?

**Comment by pvaneck** [comment]
@yuzisun Sure, just rebased now.

**Comment by yuzisun** [comment]
> @yuzisun Sure, just rebased now.

I will merge once CI is passed! thanks!

**Comment by yuzisun** [comment]
thanks @pvaneck ! we are all good, can cut the 0.4.1 release now.

/lgtm
/approve

**Pull request merged**
